### PR TITLE
update(policies): setup for policy hub

### PR DESCRIPTION
**Pull request by ajithsimons**
## Description
- setup for policy hub

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by sachinargade123 — APPROVED** [review]
LGTM

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Review by sachinargade123 — APPROVED** [review]
LGTM

**Review by adityagajbhiye9 — CHANGES_REQUESTED** [review]
@ajithsimons Please check copy right

**Comment by adityagajbhiye9** [comment]
@ajithsimons 

> Please be aware of the license header years! If you create a new file, just put the current year in it. For other (modified) files you can either have 1 year (creation year) (e.g. 2024) or a 2 year range (creation year and last modification year) with commas separated (e.g. 2019,2024)

Asked team to update Thanks.

**Review by adityagajbhiye9 — CHANGES_REQUESTED** [review]
@ajithsimons  Please check this one.

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Review by almadigabor — APPROVED** [review]
LGTM

**Pull request merged**
