### PR TITLE
chore(docs): docs and change log updated

### PR DESCRIPTION
**Pull request by ajithsimons**
## Description

- Change log updated
- Docs updated
- PNG and other format images converted into SVG format

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Comment by almadigabor** [comment]
Please take a look at this [TRG](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4#description) and adjust your images accordingly.

**Review by adityagajbhiye9 — APPROVED** [review]
@ajithsimons we need to save image in .svg format. 
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4/#description
please have a look above URL

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Comment by adityagajbhiye9** [comment]
@sachinargade123  please review

**Comment by almadigabor** [comment]
Looks good, but I still have 2 remarks to consider:

- The documentation contains ArgoCD description which in my opinion does not make much sense in open source as we use ArgoCD in specific environments only.
- You could reference the move from png to svc in the PR description/changelog

**Comment by AjayRaturi123** [comment]
@almadigabor Argocd reference removed from documents.

**Review by sachinargade123 — APPROVED** [review]
Looks good to me

**Comment by adityagajbhiye9** [comment]
merge before #65

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
