### PR TITLE
[Fix:sde-frontend] docker image security fix- v2.3.3

### PR DESCRIPTION
**Pull request by adityagajbhiye9**
## Description
- Docker image change to fix security issues of Image.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by adkumar1 — APPROVED** [review]
Changes looks good & tested the image.

**Comment by FaGru3n** [comment]
Did you also rechecked your image against our following TRG https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02

**Comment by adityagajbhiye9** [comment]
> Did you also rechecked your image against our following TRG https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02

Yes,I have rechecked image.

**Comment by FaGru3n** [comment]
hi @adityagajbhiye9 is this also clarified with Release-Management that your update your helm chart that is approved already tue the QG-Checks?

**Comment by adityagajbhiye9** [comment]
> hi @adityagajbhiye9 is this also clarified with Release-Management that your update your helm chart that is approved already tue the QG-Checks?

@FaGru3n Yes, Can i mark as unreleased? yesterday trivy reported issue.

**Comment by adityagajbhiye9** [comment]
@FaGru3n Can I closed this pull request?
I have re-run the image(older image) and it doesn't show any issues.
https://github.com/catenax-ng/tx-managed-simple-data-exchanger-frontend/security/code-scanning?query=is%3Aopen+branch%3Afix
may be false alert.

**Comment by adityagajbhiye9** [comment]
Closing PR.

**Pull request closed without merging**
