### PR TITLE
docs: change log updated 

### PR DESCRIPTION
**Pull request by ajithsimons**
## Description

- change log updated
- user guide updated

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by sachinargade123 — APPROVED** [review]
LGTM

**Comment by adityagajbhiye9** [comment]
@ajithsimons  What is know defects?

**Review by adityagajbhiye9 — CHANGES_REQUESTED** [review]
Please mark as a fixed.
Thanks.

**Comment by adityagajbhiye9** [comment]
@almadigabor  Please review and merge.

**Pull request merged**
