### PR TITLE
[chore]: Code refactor: File download from server and page layout

### PR DESCRIPTION
**Pull request by ajithsimons**
## Description

- Download file functions code optimisations. 
- Page layout css fixes.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by ajithsimons** [comment]
Please Merge this PR after #43 

@dvasunin  Please review it.

@FaGru3n  Please merge after review.

**Review by dvasunin — APPROVED** [review]
LGTM

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Review by hzierer — APPROVED** [review]
LGTM

**Pull request merged**
