### PR TITLE
fix(policy): Latest Purpose policy version updated

### PR DESCRIPTION
**Pull request by ajithsimons**
## Description

Latest Purpose policy version ID 3.1 Trace updated.

## Pre-review checks

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by ajithsimons** [comment]
@sachinargade123  @adityagajbhiye pls review.

**Review by sachinargade123 — APPROVED** [review]
LGTM

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Comment by adityagajbhiye9** [comment]
merge this PR after #55

**Review by almadigabor — APPROVED** [review]
LGTM

**Pull request merged**
