### PR TITLE
[feat:sde-v2.0.8] contract end date from usage policy duration 

### PR DESCRIPTION
**Pull request by adityagajbhiye9**
## Description
- removed the older charts.
- contract end date from usage policy duration.
- updated the document.
- chart releaser workflow update.
- dockerhub image push workflow update.
- sonarcloud reliability bug fix.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up to date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] Copyright and license header are present on all affected files

### Additional information

- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if you are unsure, who to contact, or if want to engage in a general discussion
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation contribution guidelines](https://www.eclipse.org/projects/handbook/#contributing)

### CODE REVIEW

**Comment by adityagajbhiye9** [comment]
@ajithsimons  Please review and check for dependencies and tick the check box.

**Comment by adityagajbhiye9** [comment]
closing this PR for rechecking .

**Comment by almadigabor** [comment]
Please add missing license headers to your files. Also run dash-tool to check if your dependency licenses are up to date!

**Comment by adityagajbhiye9** [comment]
license header added. and dependency run checked.

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
