### PR TITLE
fix(user manual link): Dynamic url based on release tag

### PR DESCRIPTION
**Pull request by ajithsimons**
## Description

Generate user manual link based on release tag

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by ajithsimons** [comment]
@sachinargade123  @adityagajbhiye  Please review.

**Review by sachinargade123 — APPROVED** [review]
LGTM

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Comment by adityagajbhiye9** [comment]
please merge PR after #54

**Review by almadigabor — APPROVED** [review]
LGTM

**Pull request merged**
