### PR TITLE
[fix]: Missing license headers and generic bug fixes

### PR DESCRIPTION
**Pull request by ajithsimons**
## Description
- Data table pagination not working - fixed
- Veracode vulnerability fixes
- Missing license headers added 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by dvasunin — APPROVED** [review]
LGTM

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Review by FaGru3n — CHANGES_REQUESTED** [review]
i think this a bit outdated information for fixing the heades and so on... and i hope this is the last one...

 docker build workflow and triviy updates seems doubled

Could you please rebase it from eclipse tractus-x main branch for sde-frontend or create a new on based on the current information on main branch?

i guess then a lot changes will be not shown in this PR and than again you can update your DEPENDENCIES File

**Comment by adityagajbhiye9** [comment]
> i think this a bit outdated information for fixing the licence headers and so on...
> 
> docker build workflow and triviy updates seems doubled
> 
> Could you please rebase it from eclipse tractus-x main branch for sde-frontend or create a new on based on the current information on main branch?

Sure, Working on it.

**Comment by ajithsimons** [comment]
> Please update your DEPENDENCIES file again. It seems there was an update of "npm/npmjs/@babel/code-frame"

Done.

**Review by hzierer — APPROVED** [review]

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Comment by FaGru3n** [comment]
Hi @ajithsimons @adityagajbhiye9 @dvasunin, 

i am guessing you are doing a lot for this project and for me i am thankful to be part of such big group, but keep in mind small changes (docs / linting / pagination / code scans ) in single , separated and small pull-requests can help everyone in our hole product Tractus-X to understand what you want to achive with your product.

For now i would merge it for now to come forward with our Release, but everytime keep in mind our TRG´s that we and all other committers are updating regularly. 

And maybe this will also lead someone of you into in committers postion that can also merge/ verify others PR´s (reminder Office Hour, Mailing List, Tractus-X Matrix Chat)...

**Review by FaGru3n — APPROVED** [review]
LGTM for now, without content check but TRG checks

**Comment by ajithsimons** [comment]
@FaGru3n  Thank you for your valuable suggestions! They give me more motivation to improve my work.

**Pull request merged**
