### PR TITLE
[feat]: PCF Submodel support in SDE Frontend

### PR DESCRIPTION
**Pull request by ajithsimons**
## Description

- PCF Submodel support added

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by ajithsimons** [comment]
Merge this PR before #43  

@dvasunin  Please review it.

@FaGru3n  Please merge after review.

**Comment by FaGru3n** [comment]
@ajithsimons just remark you can also directly add some reviewers into your PR´s and a little reminder for conventional commit´s https://www.conventionalcommits.org/en/v1.0.0/

**Review by dvasunin — APPROVED** [review]
LGTM

**Comment by FaGru3n** [comment]
Hi @ajithsimons and mixing features with chores is also not a good approach IMHO.

**Comment by ajithsimons** [comment]
> Hi @ajithsimons and mixing features with chores is also not a good approach IMHO.

Duly Noted, Since it's a minor change I have added along. Will correct it in future.

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Review by FaGru3n — APPROVED** [review]
LGTM - reminder can not verify funtion only working model and TRG related information

**Pull request merged**
